name: CloudSoft CI/CD

on:
  push:
    branches:
    - "main"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Check out repository
      uses: actions/checkout@v4

    - name: Restore dependencies
      run: dotnet restore

    - name: Build and publish
      run: |
        dotnet build --no-restore
        dotnet publish -c Release -o ./publish        

    - name: Upload app artifacts
      uses: actions/upload-artifact@v4
      with:
        name: app-artifacts
        path: ./publish

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: app-artifacts
        path: ./artifacts

    - name: Stop application
      run: |
        sudo systemctl stop GithubActionsDemo.service || true
        
    - name: Deploy application
      run: |
        sudo mkdir -p /opt/CloudSoft
        sudo cp -r ./artifacts/* /opt/CloudSoft/
        
    - name: Create service file if not exists
      run: |
        if [ ! -f /etc/systemd/system/CloudSoft.service ]; then
          sudo tee /etc/systemd/system/CloudSoft.service > /dev/null << 'EOF'
          [Unit]
          Description=CloudSoft ASP.NET Web App

          [Service]
          WorkingDirectory=/opt/CloudSoft
          ExecStart=/usr/bin/dotnet /opt/CloudSoft/CloudSoft.dll
          Restart=always
          RestartSec=10
          KillSignal=SIGINT
          SyslogIdentifier=CloudSoft
          User=www-data
          Environment=ASPNETCORE_ENVIRONMENT=Production
          Environment=DOTNET_PRINT_TELEMETRY_MESSAGE=false
          Environment="ASPNETCORE_URLS=http://*:5000"

          [Install]
          WantedBy=multi-user.target
          EOF
          
          sudo systemctl daemon-reload
          sudo systemctl enable CloudSoft.service
        fi
        
    - name: Fix permissions and start service
      run: |
        sudo chown -R www-data:www-data /opt/CloudSoft
        sudo chmod -R 755 /opt/CloudSoft
        sudo systemctl start CloudSoft.service
