name: HTTP Port 80 Kontroll

on:
  push:
    branches: [ main, master, develop ]
    paths:
      - '**networking.bicep'
  pull_request:
    branches: [ main, master, develop ]
    paths:
      - '**networking.bicep'
  workflow_dispatch:  # Tillåter manuell körning

jobs:
  check-http-port-80:
    name: Kontrollera HTTP Port 80 Konfiguration
    runs-on: ubuntu-latest
    
    steps:
      - name: Checka ut koden
        uses: actions/checkout@v3
      
      - name: Kontrollera att port 80 är öppen från internet till Reverse Proxy
        run: |
          echo "Kontrollerar att port 80 är öppen från internet till Reverse Proxy..."
          
          # Sök efter relevanta regler i reverseProxyNsg
          if grep -q "name: 'AllowHttpInbound'" networking.bicep && \
             grep -q "sourceAddressPrefix: 'Internet'" networking.bicep && \
             grep -q "destinationPortRange: '80'" networking.bicep; then
            echo "✓ Port 80 är korrekt öppen från internet till Reverse Proxy."
            exit 0
          else
            echo "Fel: Kunde inte bekräfta att port 80 är öppen från internet till Reverse Proxy!"
            echo "Kontrollera att följande finns i networking.bicep:"
            echo "- En regel med namn 'AllowHttpInbound'"
            echo "- sourceAddressPrefix inställd på 'Internet'"
            echo "- destinationPortRange inställd på '80'"
            echo "- Regeln finns i reverseProxyNsg"
            exit 1
          fi
